// Every 90x icon from one drawing (src/lib/brand/mark-svg.ts): the favicon
// (SVG and ICO), the iOS Home Screen icon, the manifest icons and the iOS
// launch images. First measures Sora and writes the mark's geometry to
// src/lib/brand/mark-geometry.ts, which the loading splash and the link card
// also draw from. Output is committed.
// Usage: bun run scripts/make-icons.ts && bunx oxfmt
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "opentype.js";
import sharp from "sharp";
import { encodeIco } from "@/lib/brand/ico";
import { LAUNCH_IMAGES, launchImageHref, launchImagePixels, SPLASH_MARK_SIZE } from "@/lib/brand/launch-images";
import { BRAND_COLORS, layoutMark, MARK_BOX, MARK_FONT_SIZE } from "@/lib/brand/mark";
import { markElements, type MarkGeometry, markSvg } from "@/lib/brand/mark-svg";

const root = process.cwd();
const round = (n: number) => Math.round(n * 1000) / 1000;

/** Measure "90" and the x-height in Sora 700 and place the mark (brand mock, layoutLogos). */
async function measure(): Promise<MarkGeometry> {
  const ttf = await readFile(path.join(root, "assets", "fonts", "sora-700.ttf"));
  const font = parse(ttf.buffer.slice(ttf.byteOffset, ttf.byteOffset + ttf.byteLength));
  // Pen at x 0 on baseline 0; y grows downward as in SVG.
  const ninety = font.getPath("90", 0, 0, MARK_FONT_SIZE).getBoundingBox();
  const ex = font.getPath("x", 0, 0, MARK_FONT_SIZE).getBoundingBox();
  const layout = layoutMark({ inkLeft: ninety.x1, inkRight: ninety.x2, capHeight: -ninety.y1, xHeight: -ex.y1 });
  const [one, two] = layout.strokes.map((l) => ({ x1: round(l.x1), y1: round(l.y1), x2: round(l.x2), y2: round(l.y2) }));
  if (!one || !two) throw new Error("the x needs two strokes");
  return {
    ninety: font.getPath("90", layout.textX, layout.baseline, MARK_FONT_SIZE).toPathData({ decimalPlaces: 2, flipY: false }),
    width: round(layout.width),
    strokes: [one, two],
  };
}

async function writeGeometry(geometry: MarkGeometry) {
  const source = `// Generated by scripts/make-icons.ts from Sora 700. Don't edit; run the script.
import type { MarkGeometry } from "./mark-svg";

export const MARK: MarkGeometry = ${JSON.stringify(geometry, null, 2)};
`;
  await writeFile(path.join(root, "src", "lib", "brand", "mark-geometry.ts"), source);
}

const png = (svg: string) => sharp(Buffer.from(svg)).png({ compressionLevel: 9 });

async function save(file: string, svg: string) {
  await mkdir(path.dirname(file), { recursive: true });
  await png(svg).toFile(file);
  console.log(path.relative(root, file));
}

/** The mark without a tile at the splash's size, centred on the app background at device pixels. */
function launchSvg(width: number, height: number, scale: number, geometry: MarkGeometry): string {
  const s = SPLASH_MARK_SIZE / MARK_BOX;
  const x = (width - SPLASH_MARK_SIZE) / 2;
  const y = (height - SPLASH_MARK_SIZE) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width * scale}" height="${height * scale}" viewBox="0 0 ${width} ${height}"><rect width="${width}" height="${height}" fill="${BRAND_COLORS.bg}"/><g transform="translate(${x} ${y}) scale(${s})">${markElements(geometry)}</g></svg>`;
}

const geometry = await measure();
await writeGeometry(geometry);
console.log("src/lib/brand/mark-geometry.ts");

const app = path.join(root, "src", "app");
const icons = path.join(root, "public", "icons");

await writeFile(path.join(app, "icon.svg"), `${markSvg(geometry, { size: MARK_BOX, tile: "rounded" })}\n`);
console.log("src/app/icon.svg");

const ico = await Promise.all(
  [16, 32, 48].map(async (size) => ({ size, png: await png(markSvg(geometry, { size, tile: "rounded" })).toBuffer() })),
);
await writeFile(path.join(app, "favicon.ico"), encodeIco(ico));
console.log("src/app/favicon.ico");

// iOS rounds the corners itself and shows transparency as black, so edge to edge.
await save(path.join(app, "apple-icon.png"), markSvg(geometry, { size: 180, tile: "square", fraction: 0.58 }));

for (const size of [192, 512]) {
  await save(path.join(icons, `icon-${size}.png`), markSvg(geometry, { size, tile: "rounded" }));
  // Launchers crop maskable icons to their own shape: keep the mark inside the central safe circle.
  await save(path.join(icons, `icon-maskable-${size}.png`), markSvg(geometry, { size, tile: "square", fraction: 0.56 }));
}

for (const screen of LAUNCH_IMAGES) {
  const { width, height } = launchImagePixels(screen);
  const file = path.join(root, "public", launchImageHref(screen));
  await save(file, launchSvg(screen.width, screen.height, screen.scale, geometry));
  const meta = await sharp(file).metadata();
  if (meta.width !== width || meta.height !== height) throw new Error(`${file}: ${meta.width}×${meta.height}, want ${width}×${height}`);
}
